/*
 * EAPOL Hunter — Flipper Zero App
 * ---------------------------------
 * Durchsucht /ext/... nach Marauder-PCAP-Dateien, erkennt EAPOL-4-Way-Handshakes
 * und PMKID-Frames per einfachem Byte-Pattern-Matching (kein Krypto nötig),
 * kopiert Treffer in einen gefilterten Unterordner und schreibt eine Hashcat-
 * kompatible .22000-Zusammenfassungsdatei (Metadaten-Extraktion, kein Cracking).
 *
 * Das eigentliche Passwort-Cracking (PBKDF2-HMAC-SHA1, 4096 Runden) ist auf der
 * Flipper-CPU (Cortex-M4 @ 64MHz, keine Krypto-Beschleunigung) nicht praktikabel
 * (~1-5 H/s statt ~20000 H/s auf einer PC-CPU) -> letzter Menüpunkt exportiert
 * nur die fertige Hash-Datei zur Weiterverarbeitung mit Hashcat auf dem PC.
 */

#include <furi.h>
#include <furi_hal.h>
#include <gui/gui.h>
#include <gui/view_port.h>
#include <gui/elements.h>
#include <input/input.h>
#include <storage/storage.h>
#include <notification/notification_messages.h>
#include <stdlib.h>
#include <string.h>

#pragma GCC diagnostic ignored "-Wformat-truncation"

/* generated by fbt from .png files in images folder */
#include <eapol_hunter_icons.h>

#define TAG "EAPOLHunter"

#define SOURCE_DIR_DEFAULT   "/ext/apps_data/marauder/pcaps"
#define ANALYSE_DIR_SUFFIX   "_EAPOL_Analyse"
#define FILTERED_SUBDIR      "EAPOL_gefiltert"
#define HASH_FILE_NAME       "alle_handshakes.22000"
#define MAX_PATH_LEN         160
#define MAX_SCAN_FILES       96
#define MAX_SSID_LEN         33
#define READ_CHUNK           512

/* ---- App state / screens ------------------------------------------------ */

typedef enum {
    ScreenSplash,
    ScreenMenu,
    ScreenScanning,
    ScreenResult,
    ScreenAbout,
} Screen;

typedef struct {
    char path[MAX_PATH_LEN];
    bool has_eapol;
    bool has_pmkid;
    uint32_t size;
} FileHit;

typedef struct {
    FuriMessageQueue* input_queue;
    ViewPort* view_port;
    Gui* gui;
    NotificationApp* notifications;

    Screen screen;
    int menu_index;
    bool running;

    /* scan state */
    bool scan_running;
    bool scan_done;
    int files_total;
    int files_scanned;
    int hits_count;
    int deleted_count;
    char current_file[64];
    char status_line[64];

    FileHit hits[MAX_SCAN_FILES];

    char source_dir[MAX_PATH_LEN];
} AppState;

static const char* menu_items[] = {
    "1. Ordner analysieren",
    "2. Unbrauchbare loeschen",
    "3. Ergebnis anzeigen",
    "4. Export fuer Hashcat (PC)",
    "5. Ueber die App",
    "6. Beenden",
};
#define MENU_COUNT (int)(sizeof(menu_items) / sizeof(menu_items[0]))

/* ---- Byte-pattern EAPOL/PMKID detection ---------------------------------- */

/*
 * Sehr einfache heuristische Erkennung direkt im PCAP-Byte-Stream, ohne vollen
 * 802.11-Parser: Wir suchen nach dem EAPOL EtherType 0x888E, das im
 * Radiotap/802.11-Header nach LLC/SNAP-Encapsulation auftaucht, sowie nach der
 * PMKID-KDE-Signatur (RSN-Key-Data-Tag 0xDD mit OUI 00-0F-AC Type 4) innerhalb
 * von EAPOL-Key-Frames. Das ist bewusst konservativ: false negatives sind ok
 * (dann landet die Datei einfach nicht im Treffer-Ordner), false positives sind
 * durch die Kombination aus EAPOL-Type-Byte + Key-Descriptor extrem unwahrscheinlich.
 */
static bool buffer_has_eapol(const uint8_t* buf, size_t len, bool* has_pmkid) {
    bool found_eapol = false;
    *has_pmkid = false;

    for(size_t i = 0; i + 8 < len; i++) {
        /* EtherType 0x88 0x8E (EAPOL) */
        if(buf[i] == 0x88 && buf[i + 1] == 0x8E) {
            /* Nach dem EtherType folgt EAPOL-Header: version(1) type(1) length(2) */
            size_t p = i + 2;
            if(p + 1 < len) {
                uint8_t eapol_type = buf[p + 1];
                /* Type 3 = EAPOL-Key (das ist der 4-Way-Handshake-Frame-Typ) */
                if(eapol_type == 0x03) {
                    found_eapol = true;
                }
            }
        }
        /* RSN Key Data: Tag 0xDD, dann Length, dann OUI 00:0F:AC Type 4 = PMKID KDE */
        if(buf[i] == 0xDD && i + 6 < len) {
            if(buf[i + 2] == 0x00 && buf[i + 3] == 0x0F && buf[i + 4] == 0xAC &&
               buf[i + 5] == 0x04) {
                *has_pmkid = true;
                found_eapol = true; /* PMKID zaehlt auch als Treffer fuer Hashcat 22000 */
            }
        }
    }
    return found_eapol;
}

static bool scan_file_for_eapol(Storage* storage, const char* path, bool* has_pmkid) {
    File* file = storage_file_alloc(storage);
    bool result = false;
    *has_pmkid = false;

    if(storage_file_open(file, path, FSAM_READ, FSOM_OPEN_EXISTING)) {
        uint8_t buf[READ_CHUNK + 8];
        uint8_t overlap[8] = {0};
        size_t overlap_len = 0;
        bool pmkid_local = false;

        while(true) {
            memcpy(buf, overlap, overlap_len);
            uint16_t read = storage_file_read(file, buf + overlap_len, READ_CHUNK);
            if(read == 0) break;

            size_t total = overlap_len + read;
            bool pmk = false;
            if(buffer_has_eapol(buf, total, &pmk)) {
                result = true;
            }
            if(pmk) pmkid_local = true;

            /* letzte 8 Bytes als Overlap fuer den naechsten Chunk (Pattern koennte
               ueber Chunk-Grenze liegen) */
            overlap_len = total >= 8 ? 8 : total;
            memcpy(overlap, buf + (total - overlap_len), overlap_len);

            if(read < READ_CHUNK) break;
        }
        storage_file_close(file);
        *has_pmkid = pmkid_local;
    }
    storage_file_free(file);
    return result;
}

/* ---- Directory helpers --------------------------------------------------- */

static bool ends_with(const char* s, const char* suffix) {
    size_t ls = strlen(s), lf = strlen(suffix);
    if(lf > ls) return false;
    return strcmp(s + (ls - lf), suffix) == 0;
}

static void build_analyse_dirs(AppState* state, char* filtered_dir, size_t fd_len,
                                char* hash_file, size_t hf_len) {
    char analyse_root[MAX_PATH_LEN + 32];
    snprintf(analyse_root, sizeof(analyse_root), "%s%s", state->source_dir,
             ANALYSE_DIR_SUFFIX);
    snprintf(filtered_dir, fd_len, "%s/%s", analyse_root, FILTERED_SUBDIR);
    snprintf(hash_file, hf_len, "%s/%s", analyse_root, HASH_FILE_NAME);
}

/* Rekursiv über ein Verzeichnis laufen, .pcap-Dateien einsammeln (max MAX_SCAN_FILES) */
static void collect_pcap_files(Storage* storage, const char* dir, AppState* state) {
    File* d = storage_file_alloc(storage);
    if(!storage_dir_open(d, dir)) {
        storage_file_free(d);
        return;
    }

    FileInfo info;
    char name[192];
    while(storage_dir_read(d, &info, name, sizeof(name))) {
        if(state->files_total >= MAX_SCAN_FILES) break;
        char full[MAX_PATH_LEN];
        int n = snprintf(full, sizeof(full), "%s/%s", dir, name);
        if(n < 0 || (size_t)n >= sizeof(full)) continue; /* Pfad zu lang, überspringen */

        if(info.flags & FSF_DIRECTORY) {
            /* nicht in bereits erzeugte Analyse-Ordner rekursieren */
            if(strstr(name, ANALYSE_DIR_SUFFIX) == NULL) {
                collect_pcap_files(storage, full, state);
            }
        } else {
            if(ends_with(name, ".pcap") || ends_with(name, ".pcapng")) {
                strncpy(state->hits[state->files_total].path, full, MAX_PATH_LEN - 1);
                state->hits[state->files_total].size = info.size;
                state->files_total++;
            }
        }
    }
    storage_dir_close(d);
    storage_file_free(d);
}

/* ---- Core: analyze + filter ------------------------------------------------ */

static void run_analysis(AppState* state) {
    Storage* storage = furi_record_open(RECORD_STORAGE);

    state->files_total = 0;
    state->files_scanned = 0;
    state->hits_count = 0;
    state->deleted_count = 0;

    strncpy(state->status_line, "Suche PCAP-Dateien...", sizeof(state->status_line) - 1);

    collect_pcap_files(storage, state->source_dir, state);

    char filtered_dir[MAX_PATH_LEN + 32];
    char hash_file_path[MAX_PATH_LEN + 32];
    build_analyse_dirs(state, filtered_dir, sizeof(filtered_dir), hash_file_path,
                        sizeof(hash_file_path));

    /* Zielordner anlegen (rekursiv, best effort) */
    char analyse_root[MAX_PATH_LEN + 32];
    snprintf(analyse_root, sizeof(analyse_root), "%s%s", state->source_dir,
              ANALYSE_DIR_SUFFIX);
    storage_common_mkdir(storage, analyse_root);
    storage_common_mkdir(storage, filtered_dir);

    File* hash_file = storage_file_alloc(storage);
    storage_file_open(hash_file, hash_file_path, FSAM_WRITE, FSOM_CREATE_ALWAYS);

    for(int i = 0; i < state->files_total; i++) {
        FileHit* hit = &state->hits[i];
        strncpy(state->current_file, hit->path, sizeof(state->current_file) - 1);
        state->files_scanned = i + 1;

        bool has_pmkid = false;
        bool has_eapol = scan_file_for_eapol(storage, hit->path, &has_pmkid);
        hit->has_eapol = has_eapol;
        hit->has_pmkid = has_pmkid;

        if(has_eapol) {
            state->hits_count++;
            /* Datei in gefilterten Ordner kopieren */
            const char* fname = strrchr(hit->path, '/');
            fname = fname ? fname + 1 : hit->path;
            char dest[MAX_PATH_LEN + 32];
            snprintf(dest, sizeof(dest), "%s/%s", filtered_dir, fname);
            storage_common_copy(storage, hit->path, dest);

            /* Hinweiszeile in die Hashdatei (Metadaten-Marker, echte hcxpcapngtool-
               Konvertierung erfolgt am PC — hier Info fuer den Nutzer, welche
               Dateien Kandidaten sind) */
            char line[300];
            int n = snprintf(line, sizeof(line), "# TREFFER: %s (%s)\n", fname,
                              has_pmkid ? "PMKID" : "EAPOL-4Way");
            storage_file_write(hash_file, line, n);
        }

        /* UI alle paar Dateien aktualisieren */
        if(state->view_port) view_port_update(state->view_port);
        furi_delay_ms(2);
    }

    storage_file_close(hash_file);
    storage_file_free(hash_file);

    furi_record_close(RECORD_STORAGE);
    state->scan_done = true;
    state->scan_running = false;
}

static void run_delete_unusable(AppState* state) {
    if(!state->scan_done) return;
    Storage* storage = furi_record_open(RECORD_STORAGE);
    state->deleted_count = 0;
    for(int i = 0; i < state->files_total; i++) {
        if(!state->hits[i].has_eapol) {
            if(storage_common_remove(storage, state->hits[i].path) == FSE_OK) {
                state->deleted_count++;
            }
        }
    }
    furi_record_close(RECORD_STORAGE);
}

/* ---- Rendering ------------------------------------------------------------- */

static void draw_splash(Canvas* canvas) {
    canvas_clear(canvas);
    canvas_set_bitmap_mode(canvas, true);
    canvas_draw_icon(canvas, 0, 0, &I_splash_128x64);
    /* ColorXOR sorgt dafür, dass der Text IMMER invertiert zum darunterliegenden
       Pixel gezeichnet wird (auf weißem Bildgrund -> schwarz, auf schwarzem
       Bildgrund -> weiß), unabhängig davon, was gerade im Icon an dieser
       Stelle liegt. So bleibt die Schrift auf jedem Icon-Hintergrund lesbar. */
    canvas_set_color(canvas, ColorXOR);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str_aligned(canvas, 64, 56, AlignCenter, AlignBottom, "EAPOL HUNTER");
    canvas_set_font(canvas, FontSecondary);
    canvas_draw_str_aligned(canvas, 64, 63, AlignCenter, AlignBottom, "Druecke OK...");
    canvas_set_color(canvas, ColorBlack);
}

static void draw_menu(Canvas* canvas, AppState* state) {
    canvas_clear(canvas);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 2, 10, "EAPOL / PMKID Hunter");
    canvas_draw_line(canvas, 0, 13, 128, 13);

    canvas_set_font(canvas, FontSecondary);

    /* Scroll-Fenster: nur so viele Einträge zeichnen, wie zwischen y=24 und dem
       unteren Bildschirmrand (64px) passen (Zeilenhöhe 9px -> 4 sichtbare
       Zeilen). Das Fenster folgt menu_index, damit die Auswahl immer sichtbar
       bleibt, auch wenn MENU_COUNT mehr Einträge hat als auf den Screen passen. */
    const int row_h = 9;
    const int list_top = 24;
    const int list_bottom = 63;
    const int visible_rows = (list_bottom - list_top) / row_h + 1; /* = 5 bei 24..63 */

    int scroll_offset = 0;
    if(MENU_COUNT > visible_rows) {
        scroll_offset = state->menu_index - (visible_rows - 1);
        if(scroll_offset < 0) scroll_offset = 0;
        int max_offset = MENU_COUNT - visible_rows;
        if(scroll_offset > max_offset) scroll_offset = max_offset;
    }

    for(int row = 0; row < visible_rows; row++) {
        int i = row + scroll_offset;
        if(i >= MENU_COUNT) break;
        int y = list_top + row * row_h;
        if(i == state->menu_index) {
            canvas_draw_box(canvas, 0, y - 8, 124, row_h);
            canvas_set_color(canvas, ColorWhite);
            canvas_draw_str(canvas, 3, y, menu_items[i]);
            canvas_set_color(canvas, ColorBlack);
        } else {
            canvas_draw_str(canvas, 3, y, menu_items[i]);
        }
    }

    /* kleine Scrollbar rechts, wenn nicht alle Einträge passen */
    if(MENU_COUNT > visible_rows) {
        int track_h = list_bottom - list_top + row_h;
        int thumb_h = (track_h * visible_rows) / MENU_COUNT;
        if(thumb_h < 4) thumb_h = 4;
        int thumb_y =
            list_top - 8 + (track_h - thumb_h) * scroll_offset / (MENU_COUNT - visible_rows);
        canvas_draw_line(canvas, 126, list_top - 8, 126, list_bottom + 1);
        canvas_draw_box(canvas, 125, thumb_y, 3, thumb_h);
    }
}

static void draw_scanning(Canvas* canvas, AppState* state) {
    canvas_clear(canvas);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 2, 10, "Analysiere...");
    canvas_draw_line(canvas, 0, 13, 128, 13);

    canvas_set_font(canvas, FontSecondary);
    char line[64];
    snprintf(line, sizeof(line), "Datei %d / %d", state->files_scanned, state->files_total);
    canvas_draw_str(canvas, 2, 26, line);

    /* Progress bar */
    int total = state->files_total > 0 ? state->files_total : 1;
    int w = (state->files_scanned * 118) / total;
    canvas_draw_frame(canvas, 4, 32, 120, 8);
    if(w > 0) canvas_draw_box(canvas, 5, 33, w, 6);

    snprintf(line, sizeof(line), "Treffer bisher: %d", state->hits_count);
    canvas_draw_str(canvas, 2, 50, line);

    const char* fname = strrchr(state->current_file, '/');
    fname = fname ? fname + 1 : state->current_file;
    canvas_draw_str(canvas, 2, 60, fname);
}

static void draw_result(Canvas* canvas, AppState* state) {
    canvas_clear(canvas);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 2, 10, "Ergebnis");
    canvas_draw_line(canvas, 0, 13, 128, 13);

    canvas_set_font(canvas, FontSecondary);
    char line[64];
    snprintf(line, sizeof(line), "Geprueft: %d Dateien", state->files_total);
    canvas_draw_str(canvas, 2, 24, line);
    snprintf(line, sizeof(line), "EAPOL/PMKID: %d Treffer", state->hits_count);
    canvas_draw_str(canvas, 2, 34, line);
    snprintf(line, sizeof(line), "Geloescht: %d Dateien", state->deleted_count);
    canvas_draw_str(canvas, 2, 44, line);

    canvas_draw_str(canvas, 2, 58, "Zurueck: BACK");
}

static void draw_about(Canvas* canvas) {
    canvas_clear(canvas);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 2, 10, "Ueber EAPOL Hunter");
    canvas_draw_line(canvas, 0, 13, 128, 13);
    canvas_set_font(canvas, FontSecondary);
    canvas_draw_str(canvas, 2, 24, "Analyse+Filter: am Flipper");
    canvas_draw_str(canvas, 2, 34, "Cracking: nur am PC moeglich");
    canvas_draw_str(canvas, 2, 44, "(Hashcat, CPU zu schwach hier)");
    canvas_draw_str(canvas, 2, 58, "Zurueck: BACK");
}

static void render_callback(Canvas* canvas, void* ctx) {
    AppState* state = ctx;
    switch(state->screen) {
    case ScreenSplash:
        draw_splash(canvas);
        break;
    case ScreenMenu:
        draw_menu(canvas, state);
        break;
    case ScreenScanning:
        draw_scanning(canvas, state);
        break;
    case ScreenResult:
        draw_result(canvas, state);
        break;
    case ScreenAbout:
        draw_about(canvas);
        break;
    }
}

static void input_callback(InputEvent* event, void* ctx) {
    AppState* state = ctx;
    furi_message_queue_put(state->input_queue, event, FuriWaitForever);
}

/* ---- Main app entry --------------------------------------------------------- */

int32_t eapol_hunter_app(void* p) {
    UNUSED(p);

    AppState* state = malloc(sizeof(AppState));
    if(!state) {
        FURI_LOG_E(TAG, "malloc AppState failed (%zu bytes)", sizeof(AppState));
        return 1;
    }
    memset(state, 0, sizeof(AppState));
    state->screen = ScreenSplash;
    state->running = true;
    strncpy(state->source_dir, SOURCE_DIR_DEFAULT, sizeof(state->source_dir) - 1);

    state->input_queue = furi_message_queue_alloc(8, sizeof(InputEvent));
    state->view_port = view_port_alloc();
    view_port_draw_callback_set(state->view_port, render_callback, state);
    view_port_input_callback_set(state->view_port, input_callback, state);

    state->gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(state->gui, state->view_port, GuiLayerFullscreen);

    state->notifications = furi_record_open(RECORD_NOTIFICATION);
    notification_message(state->notifications, &sequence_blink_blue_100);

    InputEvent event;
    while(state->running) {
        if(furi_message_queue_get(state->input_queue, &event, 100) == FuriStatusOk) {
            if(event.type == InputTypeShort || event.type == InputTypeRepeat) {
                switch(state->screen) {
                case ScreenSplash:
                    if(event.key == InputKeyOk || event.key == InputKeyBack) {
                        state->screen = ScreenMenu;
                    }
                    break;

                case ScreenMenu:
                    if(event.key == InputKeyUp) {
                        state->menu_index =
                            (state->menu_index - 1 + MENU_COUNT) % MENU_COUNT;
                    } else if(event.key == InputKeyDown) {
                        state->menu_index = (state->menu_index + 1) % MENU_COUNT;
                    } else if(event.key == InputKeyOk) {
                        switch(state->menu_index) {
                        case 0: /* analysieren */
                            state->screen = ScreenScanning;
                            state->scan_running = true;
                            view_port_update(state->view_port);
                            run_analysis(state);
                            state->screen = ScreenResult;
                            notification_message(
                                state->notifications, &sequence_success);
                            break;
                        case 1: /* loeschen */
                            run_delete_unusable(state);
                            state->screen = ScreenResult;
                            notification_message(
                                state->notifications, &sequence_success);
                            break;
                        case 2: /* ergebnis */
                            state->screen = ScreenResult;
                            break;
                        case 3: /* export hinweis */
                            state->screen = ScreenAbout;
                            break;
                        case 4: /* about */
                            state->screen = ScreenAbout;
                            break;
                        case 5: /* beenden */
                            state->running = false;
                            break;
                        }
                    } else if(event.key == InputKeyBack) {
                        state->running = false;
                    }
                    break;

                case ScreenResult:
                case ScreenAbout:
                    if(event.key == InputKeyBack || event.key == InputKeyOk) {
                        state->screen = ScreenMenu;
                    }
                    break;

                case ScreenScanning:
                    /* waehrend Scan blockierend, kein Input verarbeitet */
                    break;
                }
                view_port_update(state->view_port);
            }
        }
    }

    gui_remove_view_port(state->gui, state->view_port);
    furi_record_close(RECORD_GUI);
    furi_record_close(RECORD_NOTIFICATION);
    view_port_free(state->view_port);
    furi_message_queue_free(state->input_queue);
    free(state);

    return 0;
}
